general {
    lock_cmd = qs -c noctalia-shell ipc call lockScreen lock
    before_sleep_cmd = qs -c noctalia-shell ipc call lockScreen lock
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Lock screen after 5 minutes of inactivity
listener {
    timeout = 300
    on-timeout = qs -c noctalia-shell ipc call lockScreen lock
}

# Suspend after 10 minutes of inactivity
listener {
    timeout = 600
    on-timeout = systemctl suspend
}
